### ISSUE TITLE
Exception on reaction 3.8.0

### ISSUE THREAD

**Issue by merdiano** [outgrow/reaction-marketplace#3]
Tried with reaction 3.8.0 version by adding ` "reaction-marketplace" : "@outgrowio/reaction-marketplace"` to plugins.js
Get exception below on start.
```
12:17:23.911Z ERROR Reaction: Cannot resolve package exports target 'undefined' matched for '.' in /usr/local/src/app/node_modules/@outgrowio/reaction-marketplace/package.json, imported from /usr/local/src/app/node_modules/@reactioncommerce/api-core/src/importPluginsJSONFile.js
  Error: Cannot resolve package exports target 'undefined' matched for '.' in /usr/local/src/app/node_modules/@outgrowio/reaction-marketplace/package.json, imported from /usr/local/src/app/node_modules/@reactioncommerce/api-core/src/importPluginsJSONFile.js
      at resolve (<anonymous>)
      at Loader.resolve [as _resolve] (internal/modules/esm/default_resolve.js:84:13)
      at Loader.resolve (internal/modules/esm/loader.js:73:33)
      at Loader.getModuleJob (internal/modules/esm/loader.js:147:40)
      at Loader.import (internal/modules/esm/loader.js:131:28)
      at importModuleDynamically (internal/modules/esm/translators.js:75:23)
```

**Comment by loan-laux** [comment]
@merdiano Just pushed a fix to make this package work with Reaction 3.9. Try again and feel free to re-open if you're still experiencing this!
